[project]
name = "calculator-example"
version = "1.0.0"
description = "Complete calculator example demonstrating TDD with pytest"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.4.0",
]

[project.optional-dependencies]
dev = [
    "pytest-cov>=4.1.0",
]