services:
  # Backend Web Service
  - type: web
    name: taskflow-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install uv && uv sync
    startCommand: uv run uvicorn src.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false  # Set manually in Render dashboard
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        sync: false  # Set to your frontend URL
    healthCheckPath: /health
