name: Examples Tests

on:
  push:
    branches: ['examples']
  pull_request:
    branches: ['examples']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync

    - name: Run calculator tests
      run: uv run pytest calculator/test_calculator.py -v

    - name: Run calculator demo
      run: uv run python calculator/calculator.py